name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag serabass/node-test:latest && docker push serabass/node-test -a


# 0916f886-517d-404f-86e1-53baed650c44
